### ISSUE TITLE
Compatibility with Winston 3 ?

### ISSUE THREAD

**Issue by Zefiro** [jdthorpe/winston-log-and-exit#4]
I ran into the issue of winston file logs being truncated and wanted to try your promising variant.
However I'm getting an error:

C:\...\node_modules\winston-log-and-exit\index.js:37
winston.Logger.prototype.logAndExit =  function(level,msg,code_or_callback){
                                    ^

TypeError: Cannot set property 'logAndExit' of undefined
    at Object.<anonymous> (C:\...\node_modules\winston-log-and-exit\index.js:37:37)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\...\testWinston.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

Is it possible to adapt your code to work with the current Winston 3 version?

Thanks!

**Comment by jdthorpe** [comment]
I won't likely have time to address this in the near future, and I'd welcome a PR.  However, [this new feature](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#winstonlogger) in Winston 3.0 may be all you need.

**Comment by Zefiro** [comment]
Thanks, using standard functionality is probably the better choice.

I'm currently struggling on getting it to work, though. It seems there just isn't a clean way to prematurely exit a node script at all.
